server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.initialization-fail-timeout=-1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_AUTH_TOKEN}
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=2s
spring.data.redis.connect-timeout=2s

app.cache.ttl-seconds=${CACHE_TTL_SECONDS:60}

spring.jackson.serialization.write-dates-as-timestamps=false
